# A set of environment variables.
# DO NOT edit this file.
# Copy it to setenv.sh, edit and install with
# "source setenv.sh".
export SQUONK2_KEYCLOAK_URL="https://example.com/auth"
export SQUONK2_KEYCLOAK_REALM="squonk"
export SQUONK2_KEYCLOAK_AS_CLIENT_ID="account-server-api-test"
export SQUONK2_KEYCLOAK_DM_CLIENT_ID="data-manager-api-test"
export SQUONK2_KEYCLOAK_USER="dmit-user-admin"
export SQUONK2_KEYCLOAK_USER_PASSWORD="SetMe"

export SQUONK2_ASAPI_URL="https://example.com/account-server-api"
export SQUONK2_ASAPI_VERIFY_SSL_CERT="yes"

export SQUONK2_DMAPI_URL="https://example.com/data-manager-api"
export SQUONK2_DMAPI_VERIFY_SSL_CERT="yes"
